### ISSUE TITLE
Sequence of recording vertices and edges in g2o file

### ISSUE THREAD

**Issue by bexilin** [david-m-rosen/SE-Sync#14]
Hi, @david-m-rosen, I've been using the C++ SE-Sync tool to optimize a series of poses in SE(3) recently, and discovered that the sequence that I record vertices and edges on the g2o file (I mean in terms of id) affects the optimization result. However, it seems that there is no requirement about the sequence of id here, https://github.com/RainerKuemmerle/g2o/wiki/File-Format. Could you please clarify the required recording sequence of vertices and edges in terms of their id when using SE-Sync tool? Thank you!

**Comment by david-m-rosen** [comment]
Hi Xi,

The labels (ids) used to identify the N unknown poses should be taken from {0, ..., N-1}, but the specific assignment of labels to poses shouldn't matter (i.e., if you apply a permutation to the label assignments, you should still get the same final map). Can you share the (printed) output from a couple of these examples, and/or a (small) minimal working example that reproduces the behavior?

**Comment by bexilin** [comment]
Hi David, I test it with smallGrid3D.g2o file given in data folder, and the modification I do is simply moving the line recording the last edge in the g2o file forward, like what is shown below  
![smallGrid comparison](https://user-images.githubusercontent.com/47899007/59981565-39b03c80-95d3-11e9-8be1-a979fde31ea8.png)
Then there are some differences between the results of two g2o files. The upper two files in the screenshot shown below are the original outputs of SE-Sync that show xhat. Since they are not convenient to read, I convert them to two files shown in the bottom, where each line records a pose in the same format as g2o file, translation + quaternion. 
![trajectory comparison](https://user-images.githubusercontent.com/47899007/59981632-2651a100-95d4-11e9-80ae-57b6a6f6e22a.png)
Could you please try and see if you encounter the same problem? Thanks!

**Comment by bexilin** [comment]
To make sure if my modifications on original codes cause this problem, I re-cloned and re-compiled SE-Sync repository without any modifications, and found that the same problem did exist in the original codes. Besides, I noticed the difference is that in the two output files showing xhat results, contents in the first line are the same, but their second and third line are reversed.

**Comment by bexilin** [comment]
@david-m-rosen

**Comment by david-m-rosen** [comment]
Hi Xi, 

Thanks for providing that example.  I've somehow managed to mess up the configuration of several linear algebra libraries on my machine at the moment, so I can't run the C++ code directly right now (currently at RSS :-P), but I think I can still shed some light on what might be happening here.  

Note that you _**cannot**_ test for equality between two pose-graph SLAM solutions simply by comparing them elementwise; the gauge symmetry in the problem means that two solutions that don't have exactly the same coordinates may actually still encode the _**same**_ map -- they're just expressed in two different coordinate systems (see the discussion in [this thread](https://github.com/david-m-rosen/SE-Sync/issues/13)).  I would suggest ruling this out first.

I've reproduced your test cases, and running the MATLAB implementation on them gives the following output:

> >> measurements = load_g2o_data('smallGrid3D.g2o');
> >> [SDPval, Yopt, xhat, Fxhat, SE_Sync_info, problem_data] = SE_Sync(measurements);
> .
> .
> .
> Elapsed computation time: 0.002661 seconds
> 
> Value of SDP solution F(Y): 1025.4
> Norm of Riemannian gradient grad F(Y): 0.0357003
> Value of rounded pose estimate xhat: 1025.4
> Suboptimality bound of recovered pose estimate: -4.09273e-12

and 

> >> measurements = load_g2o_data('smallGrid3D_modified.g2o');
> >> [SDPval, Yopt, xhat, Fxhat, SE_Sync_info, problem_data] = SE_Sync(measurements);
> .
> .
> .
> Elapsed computation time: 0.001378 seconds
> 
> Value of SDP solution F(Y): 1025.4
> Norm of Riemannian gradient grad F(Y): 0.0357003
> Value of rounded pose estimate xhat: 1025.4
> Suboptimality bound of recovered pose estimate: 3.63798e-12
> 
> Total elapsed computation time: 0.210615 seconds

Note that both of these runs produce solutions with the same SDP and rounded pose estimate objective values, as they should.  Does this also happen if you run the C++ code on your examples?

**Comment by bexilin** [comment]
Hi, David, the SDP and rounded pose estimate objective values are also the same when I run C++ code on the examples, and thank you very much for your explanation, I understand what happens now :-). The results of two files can actually be transformed to each other by left multiplying a a transformation matrix in SE(3).
