### ISSUE TITLE
Compatibility with Cmake 2.8

### ISSUE THREAD

**Issue by jbriales** [david-m-rosen/SE-Sync#2]
Hi David,
When compiling the C++ implementation of SE-Sync I saw you require Cmake 3.1 as minimum version. However, for those still working in Ubuntu 14.04 the officially default (newest) version is Cmake 2.8.
I compiled SE-Sync with no problems after changing the minimum version to 2.8 and then changing the (newer) Cmake instruction `set(CMAKE_CXX_STANDARD 11)` to the older `set(CMAKE_CXX_FLAGS "-std=c+11" ${CMAKE_CXX_FLAGS})`.
So my question is: Are there more reasons why you would require Cmake 3.1? And, if not, should I make a pull request with these changes to support compatibility with usual Ubuntu 14.04 platforms?

Best,
Jesus

**Comment by david-m-rosen** [comment]
Hey Jesus, 

The only reason I used set(CMAKE_CXX_STANDARD 11) vs. the older format is simply that it seemed like the more elegant way to do it, but if this is causing problems for people on older versions of Ubuntu, I'm open to a pull request with a more backwards-compatible method.

Best,
-Dave
