### ISSUE TITLE
The newest/accelerating version compiled in ubuntu 20.04...

### ISSUE THREAD

**Issue by ModernGangster** [david-m-rosen/SE-Sync#31]
When I run "cmake..", it occurs an error in CMakeLists.txt:

CMake Error at CMakeLists.txt:73 (find_package):
  By not providing "FindSPQR.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SPQR", but
  CMake did not find one.

  Could not find a package configuration file provided by "SPQR" with any of
  the following names:

    SPQRConfig.cmake
    spqr-config.cmake

  Add the installation prefix of "SPQR" to CMAKE_PREFIX_PATH or set
  "SPQR_DIR" to a directory containing one of the above files.  If "SPQR"
  provides a separate development package or SDK, be sure it has been
  installed.

However, I have already installed libsqpr2, so I don't know what lib I should install to fix this problem.

**Comment by ModernGangster** [comment]
We followed
sudo apt-get install build-essential cmake-gui libeigen3-dev liblapack-dev libblas-dev libsuitesparse-dev
and updated the version of eigen to 3.4.0

**Comment by david-m-rosen** [comment]
Fixed with commit [bbfb262](https://github.com/david-m-rosen/SE-Sync/commit/bbfb2621fcd10670e1c7fcff66af97670607d302).

**Comment by hhhhhhhh213** [comment]
> Solved: The cmake fold in Preconditioners should be copied to C++/. Just see line 38 in C++/CMakeLists.txt.

你好，是把Preconditioners中的cmake文件替换掉C++文件中的Cmake吗？谢谢
