### ISSUE TITLE
sqrtkappa is unused

### ISSUE THREAD

**Issue by strasdat** [david-m-rosen/SE-Sync#9]
https://github.com/david-m-rosen/SE-Sync/blob/7f7f5ad90cd8e187f276aae0b6de4b693fdb394c/C%2B%2B/SE-Sync/src/SESync_utils.cpp#L285

**Comment by david-m-rosen** [comment]
Resolved in commit 82e8f0cdaf575896eb158ad7f6c7f091ab2ee3bb
